export const options = {
  acabados: [
    "Sin acabado",
    "Tubos",
    "Troquel",
    "Descolillado",
    "Descolillado negativo",
    "Transfer",
    "Corte",
    "Ojales",
    "Palos",
    "Bolsillos",
    "Laminado",
  ],
  vinyls: [
    "Vinilo",
    "Vinilo Reflectivo",
    "Vinilo Rosado",
    "Vinilo Holograma",
    "Vinilo Letras Chinas",
    "Vinilo Espejo",
    "Vinilo Fluorescente",
  ],
  choice: ["Si", "No"],
  descolillado: ["Grande", "Pequeño"],
  materials: [
    "Banner",
    "Adhesivo",
    "Panaflex",
    "Reflectivo",
    "Microperforado",
    "Lienzo",
    "Aviso Con Estructura",
    "Aviso Luminoso",
    "Aviso Luminoso 2 Caras",
    "Retablo",
    "Adhesivo + Acrílico (Pequeño)",
    "Adhesivo + Acrílico (Grande)",
  ],
  materialWidth: [60, 70, 105, 125, 150, 160],
  users: [
    " ",
    "Angélica",
    "Angi",
    "Dayana",
    "Diego",
    "Gladys Sofìa",
    "Haylin",
    "Laura",
    "Loraine",
    "Olga",
    "Oswaldo",
    "Seidy",
    "Servando",
    "Yulieth",
  ],
  userType: ["Particular", "Publicista"],
  billType: ["Recibo", "Cotización"],
};
